<?php
/*=======================================================================
| GomeyCMS - Advanced Website and Content Management System for heil.world
| #######################################################################
| Copyright (c) 2017, Arran 'Pillow'.
| https://heil.world & http://gomey.tk
| #######################################################################
| This program is free software: you can redistribute it and/or modify
| it under the terms of the GNU General Public License as published by
| the Free Software Foundation, either version 3 of the License, or
| (at your option) any later version.
| #######################################################################
| This program is distributed in the hope that it will be useful,
| but WITHOUT ANY WARRANTY; without even the implied warranty of
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
| GNU General Public License for more details.
\======================================================================*/

##### DO NOT EDIT THIS FILE #####

#### IM FUCKING WARNING YOU #####

### YOUR NAME BEGINS WITH D #####


session_start();
//error_reporting(0); // This will be done via Al13ns custom error handling

// Call core files
require_once  "engine/class.engine.php";
require_once "engine/class.users.php";

$engine = new GomeyEngine();
$users = new GomeyUsers();

// Connect to DB
$db = mysqli_connect('localhost', 'root', '', 'gomey');

$engine->CheckConn();


mysqli_query($db, "INSERT INTO data (name) VALUES ('test')");

//$result = $db->query("SELECT * FROM data", MYSQLI_USE_RESULT);
//echo $result;
